---
abstract: 'Adjusts the response Content-Type'
author:
  - 'Original author and maintainer - Tomas Doran (t0m) '
build_requires:
  Catalyst::Action::RenderView: 0
  Test::More: 0
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
  Test::WWW::Mechanize::Catalyst: 0
distribution_type: module
generated_by: 'Module::Install version 0.78'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-View-ContentNegotiation-XHTML
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Runtime: 0
  Catalyst::View::TT: 0
  HTTP::Negotiate: 0
  MRO::Compat: 0
  MooseX::Types::Moose: 0
  MooseX::Types::Structured: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://dev.catalyst.perl.org/repos/Catalyst/Catalyst-View-TT-XHTML
version: 1.101
